#!/usr/bin/env bash

declare -a required
required=(
    "bash"
    "sway"
    "tput"
    "mv"
)

for pkg in "${required[@]}"
do
    if ! command -v "$pkg" > /dev/null 2>&1
    then
        echo "Error: missing '$pkg'" >&2
        exit 1
    fi
done

# This script uses new features like ${ command; }
# BASH_VERSINFO[0] is major version; BASH_VERSINFO[1] is minor version
if (( BASH_VERSINFO[0]*100 + BASH_VERSINFO[1] < 503 ))
then
    echo "Error: Bash version is older than 5.3" >&2
    exit 1
fi

declare blk red ylw blu prp res
blk="${ tput setaf 8; }"
red="${ tput setaf 9; }"
ylw="${ tput setaf 11; }"
blu="${ tput setaf 12; }"
prp="${ tput setaf 13; }"
res="${ tput sgr0; }"

log() {
    local kind msg prompt
    kind="$1"
    msg="$2"

    local -i loglvl

    case "$kind" in
        err)
            # Urgent messages that require manual intervention
            loglvl=0
            if (( wantlvl >= loglvl ))
            then
                prompt="ERROR:"
                printf "${red}%s${res} %s\n" "$prompt" "$msg" >&2
            fi
            ;;
        warn)
            # Urgent messages that do not require manual intervention
            loglvl=1
            if (( wantlvl >= loglvl ))
            then
                prompt="WARN:"
                printf "${ylw}%s${res} %s\n" "$prompt" "$msg"
            fi
            ;;
        info)
            # Messages that report the script's general progress
            loglvl=2
            if (( wantlvl >= loglvl ))
            then
                prompt="INFO:"
                printf "${blu}%s${res} %s\n" "$prompt" "$msg"
            fi
            ;;
        extra)
            # More granular progress reports that could get annoying
            loglvl=3
            if (( wantlvl >= loglvl ))
            then
                prompt="EXTRA:"
                printf "${prp}%s${res} %s\n" "$prompt" "$msg"
            fi
            ;;
        debug)
            # Information that is primarily useful for developers but not users
            loglvl=4
            if (( wantlvl >= loglvl ))
            then
                prompt="DEBUG:"
                printf "${blk}%s${res} %s\n" "$prompt" "$msg"
            fi
            ;;
        *)
            # Default to info
            loglvl=2
            prompt="INFO:"
            printf "${blu}%s${res} %s\n" "$prompt" "$msg"
    esac
}

# Separate items with a minimum of two spaces
usage() {
    echo "Usage: ${0} [OPTIONS...] [-f FILE]"
    echo
    echo "Options:"
    echo "  -f, --file"
    echo "    Set the file to operate on"
    echo "    Can be specified more than once"
    echo
    echo "  -l, --log-level INT"
    echo "    Display logs of level INT and below"
    echo "    INT may be any natural number less than or equal to 4"
    echo "    Default is 2 (INFO)"
    echo
    echo "  -n, --no-backup"
    echo "    Do not create a FILE.bak file if FILE already exists"
    echo
    echo "  -s, --strip-characters STRING"
    echo "    Set a string of characters to strip from Sway values"
    echo "    Applies to all files provided by --file"
    echo "    Example: '--strip-characters \\\$\\\"' strips \$ and \""
    echo
    echo "  -h, --help"
    echo "    Display this message and exit"
}

log debug "Validating Sway config..."
if ! sway --validate
then
    log err "There was an error validating your Sway configuration file"
    usage >&2
    exit 1
fi

if (( $# == 0 ))
then
    log err "No arguments provided"
    usage >&2
    exit 1
fi

# Default log level is INFO
declare -i wantlvl
wantlvl=2

# Make backups by default
declare mkbkup
mkbkup="true"

# Strip nothing by default
declare chars
chars=""

declare -a files

while (( $# > 0 ))
do
    case "${1}" in
        -n|--no-backup)
            mkbkup="false"
            ;;
        -f|--file)
            files+=("${2}")
            shift
            ;;
        -l|--log-level)
            wantlvl="${2}"
            shift
            ;;
        -s|--strip-characters)
            chars="${2}"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            log err "Unknown argument: '${1}'"
            usage >&2
            exit 1
    esac
    shift
done

# TODO: Let people name associative array 
get_vars() {
    declare -gA confvars

    local -a swaylogs
    mapfile -t swaylogs < <(sway --verbose --validate 2>&1)

    local keyphrase
    keyphrase="After replacement"

    if [[ "${swaylogs[*]}" != *"$keyphrase"* ]]
    then
        log err "Keyphrase '${keyphrase}' is missing"
        log err "Some possible causes:"
        log err "  - 'sway -V -C' no longer uses keyphrase '${keyphrase}'"
        log err "  - There are no variables set in your Sway config files"
        log err "  - There is a typo in this script"
        exit 1
    fi

    for line in "${swaylogs[@]}"
    do
        if [[ "$line" == *"$keyphrase"* && "$line" =~ set\ (\$.*) ]]
        then
            declare key value
            key="${BASH_REMATCH[1]/[[:blank:]]*}"
            key="${key/\$}"
            log debug "KEY: $key"

            value="${BASH_REMATCH[1]/*\$${key}[[:blank:]]}"
            value="${value//["${chars}"]}"
            log debug "VALUE: $value"

            confvars["$key"]="$value"
        fi
    done

    log debug "CONFVARS: ${confvars[@]@K}"
}

check_file() {
    local templ ext real bkup
    templ="$1"
    ext="smxt"
    real="${templ%%."${ext}"}"
    bkup="${real}.bak"

    if [[ "${templ##*.}" != "$ext" || ! -f "$templ" ]]
    then
        log err "file '${templ}' does not use the '.${ext}' extension"
        exit 1
    fi

    # True if real file exists as regular file and user is okay with backups
    if [[ -f "$real" && "$mkbkup" == "true" ]]
    then
        log warn "'${real}' already exists! Creating backup..."
        if mv "$real" "$bkup"
        then
            log extra "Created backup file '${bkup}'"
        else
            log err "Could not create '${bkup}'! Exiting..."
            exit 1
        fi
    else
        log debug "Skipped backup; file does not exist or '--no-backup' is set"
    fi
}

apply_vars() {
    # TODO: I wonder if I could keep track of how many lines have been read from
    # ${templ} and then skip over those lines to make things faster?
    local templ ext real bkup
    templ="$1"
    ext="smxt"
    real="${templ%%."${ext}"}"
    bkup="${real}.bak"

    local -a realarr
    while read -r line
    do
        while [[ "$line" =~ (%%([^%]*)%%) ]]
        do
            local outer inner
            outer="${BASH_REMATCH[1]}"
            inner="${BASH_REMATCH[2]}"

            local value
            value="${confvars[${inner}]}"

            if [[ "$inner" =~ ^[[:blank:]%]*$ ]]
            then
                log debug "Inner was not a valid variable"
                log debug "INNER: '${inner}'"
            else
                log extra "Replacing '${inner}' with '${value}'..."
                line="${line//"${outer}"/"${value}"}"
            fi
        done
        log debug "Adding '${line}' to realarr..."
        realarr+=("$line")
    done < "${templ}"
    log debug "REALARR: '${realarr[@]}'"
    
    log debug "Overwriting '${real}' with realarr..."
    printf "%s\n" "${realarr[@]}" > "$real"
}

log info "Getting variables from Sway configuration file(s)..."
get_vars

for file in "${files[@]}"
do
    log extra "Checking validity of '${file}'..."
    check_file "${file}"
    log info "Applying Sway variables to '${file}'..."
    apply_vars "${file}"
    log extra "Finished applying variables to '${file}'"
done

exit 0
